// <auto-generated />
using EmployeeAssignmentApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeAssignmentApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("EmployeeAssignmentApp.Models.AbsentWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbsentWorkerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AbsentWorkers");
                });

            modelBuilder.Entity("EmployeeAssignmentApp.Models.Process", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedWorkerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("EmployeeAssignmentApp.Models.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ProcessWorker", b =>
                {
                    b.Property<int>("EnableProcessProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnableWorkerWorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnableProcessProcessId", "EnableWorkerWorkerId");

                    b.HasIndex("EnableWorkerWorkerId");

                    b.ToTable("ProcessWorker");
                });

            modelBuilder.Entity("ProcessWorker", b =>
                {
                    b.HasOne("EmployeeAssignmentApp.Models.Process", null)
                        .WithMany()
                        .HasForeignKey("EnableProcessProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeAssignmentApp.Models.Worker", null)
                        .WithMany()
                        .HasForeignKey("EnableWorkerWorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
